name: workflow_dispatch

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string
      command:
        required: true
        type: string

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    - name: install nix
      run: |
        yes | sh <(curl -L https://nixos.org/nix/install) --no-daemon
        mkdir -p ~/.config/nix
        echo 'system-features = nixos-test benchmark big-parallel kvm' >> ~/.config/nix/nix.conf
        echo 'experimental-features = nix-command flakes' >> ~/.config/nix/nix.conf
        set +x
        echo "access-tokens = github.com=$GITHUB_ACCESS_TOKEN" >> ~/.config/nix/nix.conf
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Run `ci.sh`
      run: |
        . ~/.nix-profile/etc/profile.d/nix.sh
        ${{ inputs.command }}